In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import sklearn

In [2]:
df=pd.read_csv("2MATCHES.csv")
df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [3]:
df.shape

(756, 18)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    str
 2   city             749 non-null    str
 3   date             756 non-null    str
 4   team1            756 non-null    str
 5   team2            756 non-null    str
 6   toss_winner      756 non-null    str
 7   toss_decision    756 non-null    str
 8   result           756 non-null    str
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    str
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    str
 14  venue            756 non-null    str
 15  umpire1          754 non-null    str
 16  umpire2          754 non-null    str
 17  umpire3          119 non-null    str
dtypes: int64(4), str(14)
memory usage: 106.4 KB

In [8]:
df.isnull().sum()

id                   0
Season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [9]:
df["city"]=df['city'].fillna('Unknown')

In [10]:
df['winner']=df['winner'].fillna('No Result')

In [11]:
df['player_of_match']=df['player_of_match'].fillna('No Award')

In [12]:
df['umpire1']=df['umpire1'].fillna('Unknown')

In [13]:
df['umpire2']=df['umpire2'].fillna('Unknown')

In [16]:
df=df.drop(columns=['umpire3'])

In [17]:
df.isnull().sum()

id                 0
Season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             0
win_by_runs        0
win_by_wickets     0
player_of_match    0
venue              0
umpire1            0
umpire2            0
dtype: int64

In [31]:
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%y')

In [33]:
df['date'].head()

0   2017-04-05
1   2017-04-06
2   2017-04-07
3   2017-04-08
4   2017-04-08
Name: date, dtype: datetime64[us]

In [34]:
df.duplicated().sum()

np.int64(0)

In [39]:
df['team1'].unique()

<StringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',      'Rising Pune Supergiant',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
              'Delhi Capitals',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors']
Length: 13, dtype: str

In [40]:
df['team2'].unique()

<StringArray>
['Royal Challengers Bangalore',      'Rising Pune Supergiant',
       'Kolkata Knight Riders',             'Kings XI Punjab',
              'Delhi Capitals',         'Sunrisers Hyderabad',
              'Mumbai Indians',               'Gujarat Lions',
            'Rajasthan Royals',         'Chennai Super Kings',
             'Deccan Chargers',               'Pune Warriors',
        'Kochi Tuskers Kerala']
Length: 13, dtype: str

In [38]:
df = df.replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
})

In [41]:
df['match_year'] = df['date'].dt.year

In [42]:
df['match_month'] = df['date'].dt.month

In [43]:
df['toss_match_win'] = (
    df['toss_winner'] == df['winner']
).astype(int)

In [44]:
df['toss_match_win']

0      0
1      1
2      1
3      1
4      1
      ..
751    1
752    0
753    1
754    1
755    1
Name: toss_match_win, Length: 756, dtype: int64

In [45]:
df.to_csv("matches_cleaned.csv", index=False)

In [48]:
deliveries = pd.read_csv("2deliveries.csv")

In [50]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [51]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  str
 3   bowling_team      179078 non-null  str
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  str
 7   non_striker       179078 non-null  str
 8   bowler            179078 non-null  str
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    str
 19  dismissal_kind    8834 non-null    str
 20  fielder           6448 non-null    str
dtypes: int64(13), str(8)
memory usage: 28.7 MB

In [52]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [55]:
deliveries.duplicated().sum()

np.int64(23)

In [56]:
deliveries = deliveries.drop_duplicates()

In [62]:
deliveries.duplicated().sum()

np.int64(0)

In [61]:
deliveries.shape

(179055, 22)

In [59]:
deliveries['is_wicket'] = deliveries['player_dismissed'].notna().astype(int)

In [66]:
deliveries[['player_dismissed','is_wicket']]

       player_dismissed  is_wicket
0                   NaN          0
1                   NaN          0
2                   NaN          0
3                   NaN          0
4                   NaN          0
...                 ...        ...
179073              NaN          0
179074              NaN          0
179075        SR Watson          1
179076              NaN          0
179077        SN Thakur          1

[179055 rows x 2 columns]

In [67]:
deliveries.info()

<class 'pandas.DataFrame'>
Index: 179055 entries, 0 to 179077
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179055 non-null  int64
 1   inning            179055 non-null  int64
 2   batting_team      179055 non-null  str
 3   bowling_team      179055 non-null  str
 4   over              179055 non-null  int64
 5   ball              179055 non-null  int64
 6   batsman           179055 non-null  str
 7   non_striker       179055 non-null  str
 8   bowler            179055 non-null  str
 9   is_super_over     179055 non-null  int64
 10  wide_runs         179055 non-null  int64
 11  bye_runs          179055 non-null  int64
 12  legbye_runs       179055 non-null  int64
 13  noball_runs       179055 non-null  int64
 14  penalty_runs      179055 non-null  int64
 15  batsman_runs      179055 non-null  int64
 16  extra_runs        179055 non-null  int64
 17  total_runs        179055 non-null  int64
 18  player_dismissed  8834 non-null    str
 19  dismissal_kind    8834 non-null    str
 20  fielder           6448 non-null    str
 21  is_wicket         179055 non-null  int64
dtypes: int64(14), str(8)
memory usage: 31.4 MB

In [72]:
deliveries['batting_team'].unique()

<StringArray>
[        'Sunrisers Hyderabad', 'Royal Challengers Bangalore',
              'Mumbai Indians',      'Rising Pune Supergiant',
               'Gujarat Lions',       'Kolkata Knight Riders',
             'Kings XI Punjab',              'Delhi Capitals',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors']
Length: 13, dtype: str

In [71]:
deliveries['bowling_team'].unique()

<StringArray>
['Royal Challengers Bangalore',         'Sunrisers Hyderabad',
      'Rising Pune Supergiant',              'Mumbai Indians',
       'Kolkata Knight Riders',               'Gujarat Lions',
             'Kings XI Punjab',              'Delhi Capitals',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors']
Length: 13, dtype: str

In [70]:
deliveries=deliveries.replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
})

In [78]:
deliveries.to_csv("deliveries_cleaned.csv", index=False)

In [74]:
##1. Top 10 Run Scorers

In [76]:
top_batsman=(
    deliveries.groupby('batsman')['batsman_runs']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

In [77]:
top_batsman

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4631
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4444
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [79]:
##2. Top 10 Wicket Takers

In [82]:
top_bowlers=(
    deliveries.groupby('bowler')['is_wicket']
    .sum()
    .sort_values(ascending=False)
    .head()
)

In [84]:
top_bowlers

bowler
SL Malinga         188
DJ Bravo           168
A Mishra           165
Harbhajan Singh    161
PP Chawla          156
Name: is_wicket, dtype: int64

In [85]:
## Most Sixes

In [86]:
sixes = (
    deliveries[deliveries['batsman_runs'] == 6]
    .groupby('batsman')
    .size()
    .sort_values(ascending=False)
    .head(10)
)

sixes

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
V Kohli           191
DA Warner         181
SR Watson         177
KA Pollard        175
YK Pathan         161
dtype: int64

In [87]:
### Most Fours

In [89]:
Fours=(
    deliveries[deliveries['batsman_runs']==4]
    .groupby('batsman')
    .size()
    .sort_values(ascending=False)
    .head(10)
)

Fours

batsman
S Dhawan      526
SK Raina      495
G Gambhir     492
V Kohli       482
DA Warner     459
RV Uthappa    436
RG Sharma     431
AM Rahane     404
CH Gayle      376
PA Patel      366
dtype: int64